# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-18 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='autorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_licencia', models.CharField(blank=True, choices=[('CC', 'Creative Commons'), ('CCR', 'Compartir con creditos del creador'), ('SL', 'Sin licencia')], max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('LG', 'Logo'), ('BR', 'Branding'), ('ED', 'Editorial'), ('PC', 'Packaging'), ('AU', 'Audio Visual')], max_length=50, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
